### PR TITLE
Improving Organization on Base Theme

### PR DESCRIPTION
**Pull request by MarceloBorgesP**
### The main changes done on this PR:

- Changing the stylesheets organization
- Changing the html pages organization
- Translating all content to english
- Fixing links (breadcrumbs mainly)
- Creating descriptions in admin
- Changing buttons
- And lots of improvements on general styling

#### Stylesheets organization

The stylesheets are well organized now, as follows:

    ├── stylesheets/
        ├── base/
            ├──dash/
            ├──others/
            ├──shop/ 
        ├── theme.less

Where:
- All stylesheets which belong to the base theme are inside the base/ folder;
- Dash refers to all stylesheets which belong to the admin's dashboard:
```
src/stylesheets/base/dash/_backs-nav.less
src/stylesheets/base/dash/_element-itens.less
src/stylesheets/base/dash/_footer.less
src/stylesheets/base/dash/_general.less
src/stylesheets/base/dash/_login.less
src/stylesheets/base/dash/_navbar.less
src/stylesheets/base/dash/_sidebar.less
```

- Shop refers to all stylesheets which belong to the store:
```
src/stylesheets/base/shop/_breadcrumb.less
src/stylesheets/base/shop/_footer.less
src/stylesheets/base/shop/_general.less
src/stylesheets/base/shop/_menu-steps.less
src/stylesheets/base/shop/_navbar.less
src/stylesheets/base/shop/_page-menu.less
src/stylesheets/base/shop/_page-title.less
src/stylesheets/base/shop/_promo-box.less
src/stylesheets/base/shop/_switching.less
src/stylesheets/base/shop/_table-cart.less
```
- Others refers to all stylesheets that are common to both Dash/ and Shop/
- theme.less is the main stylesheets, and it imports all the other ones

#### HTML Pages Organization

    ├── html/
        ├── layouts/
        ├── parts/
        ├── pages/
            ├── distributor/
            ├── reseller/
            ├── shop/
            ├── user/
            ├── docs/

Where:
- All HTML pages are inside the HTML folder
- Layout refers to all layouts on theme
- Macros contains helpers
- Parts contains some parts of HTML that are common to some pages
- Pages contain the Pages, and is divided now in **distributor**, **reseller**, **shop**, **user** and **docs**
- All Pages which their names started with **companies**, are now inside the **reseller/** folder, so now:

```
src/html/companies-categories-new.html
src/html/companies-categories-show.html
src/html/companies-categories.html
src/html/companies-groups-new.html
src/html/companies-groups-show.html
src/html/companies-groups.html
src/html/companies-new-client-entity.html
src/html/companies-new-client-person.html
src/html/companies-new.html
src/html/companies-plans.html
src/html/companies-settings.html
src/html/companies.html
```
Became:

```
src/html/pages/reseller/categories.html
src/html/pages/reseller/companies.html
src/html/pages/reseller/edit-profile.html
src/html/pages/reseller/groups.html
src/html/pages/reseller/new-category.html
src/html/pages/reseller/new-client.html
src/html/pages/reseller/new-group.html
src/html/pages/reseller/new-plan.html
src/html/pages/reseller/plans.html
src/html/pages/reseller/settings.html
src/html/pages/reseller/show-category.html
src/html/pages/reseller/show-group.html
```
- All Pages which their names started with **shop**, are now inside the **shop/** folder

```
"src/html/shop-cart-register-person.html" was deleted once it was basically the same file as "src/html/shop-cart-register-entity.html"

src/html/shop-cart-released.html → pages/shop/cart-released.html}
src/html/{shop-cart-login.html → pages/shop/cart-login.html
src/html/{shop-cart-payment.html → pages/shop/cart-payment.html
src/html/{shop-cart-register-entity.html → pages/shop/cart-register.html
src/html/pages/shop/cart-released.html
src/html/{shop-cart.html → pages/shop/cart.html
src/html/{shop-categories.html → pages/shop/categories.html
src/html/{shop-groups.html → pages/shop/groups.html
src/html/{shop-plans-customize.html → pages/shop/plans-customize.html
src/html/{shop-plans.html → pages/shop/plans.html
```

- All Pages which their names started with distributor, are now inside the distributor/ folder
- Docs is the documentation's folder
- There will be a folder to user/ as well, as soon as we create the user's pages
- All pages were renamed and inserted in one of these folders, and they are now easily accessible
- Pages such as companies-new-client-person.html and companies-new-client-entity.html which were basically the same page were put in just one page

### CODE REVIEW

**Comment by MarceloBorgesP** [comment]
If you approve this PR please send your ok @caio and @silviolrjunior, then it will be merged!

**Comment by caiohdf** [comment]
Hi @MarceloBorgesP ,

There are some considerations about this PR, and some protips about this PR that I'd like to share with you:

1. First and probably the most important: keep in mind that this project is **open source**, so everything related to proprietary stuff should be cut off the project. Internal stuff should also be cut off, like this  commit message: https://github.com/MarceloBorgesP/railsblocks-theme/commit/d29e3140b0bc5f4b69d0df71306ca109722f9cf1

2. There are 12 files deleted in this PR. Since I know that your intentions were good when you deleted those, it is fine. But I don't feel comfortable approving a PR like this without a description of what was deleted and why. So I'd like to suggest you to better describe why the files were deleted from the project.

3. There are 72 files changed in this PR. If I needed to take a surgical look at everyone of them would take me hours to review it. Try to keep your PRs shorter, or make your description better, organizing it.

4. This is a fault that happens to me too. I also need to write better commit messages. For example, "Making Some Improvements on all Base Theme", ok but which improvements? Improvements by itself is too vague. Maybe if you change it to: "working on the theme UX by change this or that" would be better.

5. You could separate your commits in "blocks" so they would be better organized and way easier to review it.

I think that is it. You did a great and huge job! Every line you changed is very important. Just need some adjusts to make it perfect :dancer: 

Thanks!

**Comment by MarceloBorgesP** [comment]
I've updated the PR's description in order to make it more understandable, see if it helps @caio .

I'm explaining how the change of structure was made, and were these files are now

**Comment by caio** [comment]
Can you please stop mentioning me when you actually mean @caiohdf ? Thanks :)

**Comment by caiohdf** [comment]
Now we're talking @MarceloBorgesP ! Nice PR description, great work on that!

Now I presume that the PR is ready to be merged.

**Comment by MarceloBorgesP** [comment]
Just wait for a last commit improving the documentation, then we can merge it real @caiohdf

**Comment by fernandes** [comment]
@MarceloBorgesP you broke the tests removing the `src/javascripts/__tests__/exclamify.test.js` we need at least one test, so we can keep the test structure ok if we need to add any.

thank you

**Comment by MarceloBorgesP** [comment]
Oh sorry, I hadn't seen your comments @fernandes , it's fixed now. I thought these files weren't being used.

It is ready to merge now!

**Comment by fernandes** [comment]
amazing description, after some feedback and improvements we reached a very good level for this PR

:+1: :tada: :boom: :shipit:

**Pull request merged**
