### PR TITLE
Feature/theme

### PR DESCRIPTION
**Pull request by caiohdf**
## Summary
This PR adds some UX improvements to the documentation, such as:
- The table of contents is now fixed to the right, even when you scroll the page;
- There are more pages on the pages description section;
- Smooth scrolling between sections;

Also, this PR contains some new pages like:
- Blog pages;
- Re-seller pages: create client entity and person;
- Distributor pages: provider editing page;

Thanks!

### CODE REVIEW

**Comment by caiohdf** [comment]
Yeaaah! You're damn right @MarceloBorgesP ! These commits are from a long time ago... Sorry for this whole misunderstanding. :flushed:

**Comment by caiohdf** [comment]
@fernandes 

Sorry again for the misunderstanding! I wrongly committed files that had already been changed. My bad! I'll pay more attention on that.

@MarceloBorgesP could you check again if this PR can be merged? If so, please comment and then @fernandes can go forward and merge it :dancer:

**Comment by MarceloBorgesP** [comment]
I think you did a great job @caiohdf!

Just small changes were necessary so it is a very good pull request.

Just something that both of us should pay attention is to make pull requests sooner, and do not let them become a pile with lots of commits. 
 As you noticed most of the commits were from many days ago, and then became obsolete. The other changes that I've pointed out in previous comments I suppose most of them were already fixed.

Just pay attention to the file html/blog-list.html, it should be inside html/pages/some_directory/ or it will break the navigation on the sidebar.

We are reaching a very good level o communication, it's important! :smile: 

I think that's all, ready to merge if everything was fixed!

**Comment by MarceloBorgesP** [comment]
So it's good to go @fernandes!

**Comment by fernandes** [comment]
good job guys! :+1: :smile_cat:

**Pull request merged**
