### PR TITLE
Reorganizing filenames for better understanding - feature/theme

### PR DESCRIPTION
**Pull request by caiohdf**
## Summary
This PR contains important changes in the railsblocks theme. As the theme is constantly growing, we need to better organize our files so we can set up git sub-modules in some directories, like the html/pages one (future thoughts :stuck_out_tongue_closed_eyes:)

So in order to keep our files organized and well named, some changes were did on the file-names.
Now the directory is organized like this:

- common/
    - login.html

- customer/
    - profile-edit-information.html

- manager/
    - new-admin-information.html
    - new-admin-providers.html
    - admin-settings-information.html
    - admin-settings-providers.html
    - admin-list.html
    - profile-edit-information.html
    - profile-edit-providers.html

- admin/
    - __settings.html
    - categories-list.html
    - category-edit.html
    - category-new.html
    - category-show.html
    - customers-list.html
    - customer-new-entity.html
    - customer-new-person.html
    - plans-list.html
    - plan-edit.html
    - plan-new.html
    - plan-show.html
    - profile-edit-information.html
    - profile-edit-providers.html
    - groups-list.html
    - group-edit.html
    - group-new.html
    - group-show.html

- shop/
    - cart-login.html
    - cart-payment.html
    - cart-register.html
    - cart-released.html
    - cart.html
    - categories.html
    - groups.html
    - plans-customize.html
    - plans.html

- docs/

Also, the documentation were updated and some unused css classes and form tags were removed.

--
**Update 15-10**: Manager's flow is now working and the its breadcrumbs were fixed.

Thanks!

### CODE REVIEW

**Comment by MarceloBorgesP** [comment]
You are very organized @caiohdf , good job! I think the documentation is becoming everyday better!

I totally approve your changes, the only mistake I pointed out was already fixed.. hehe

Just a single misspelling that needs to be fixed, and we are good to go!

**Comment by caiohdf** [comment]
Thanks @MarceloBorgesP ! The misspelling was fixed too :dancer:

**Comment by fernandes** [comment]
distributor -> manager
reseller -> admin

is the right naming on railsblocks :wink:

**Comment by caiohdf** [comment]
@MarceloBorgesP and @silviolrjunior could you guys review my last edits, please?

**Comment by silviolrjunior** [comment]
:+1:  Good job @caiohdf

**Comment by MarceloBorgesP** [comment]
Perfect @caiohdf! :smile:

**Comment by fernandes** [comment]
great!! :+1: :tada:

**Pull request merged**
