### PR TITLE
Add End Customer Edit Own profile

### PR DESCRIPTION
**Pull request by MarceloBorgesP**
screenshot from 2015-10-13 09 26 34

### CODE REVIEW

**Comment by MarceloBorgesP** [comment]
@caiohdf please review it! thanks

**Comment by caiohdf** [comment]
Hi @MarceloBorgesP 

Short and lean PR, easy to review and merge! Nice job on that!
I think is ready to be merged.

Thanks!

**Comment by MarceloBorgesP** [comment]
@fernandes another one to be merged!

**Comment by fernandes** [comment]
perfect!

**Pull request merged**
